---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits
Our project will be done using a sequence of save and commits.

## First Verse 
’Twas brillig, and the slithy toves   
      Did gyre and gimble in the wabe:   
All mimsy were the borogoves,   
      And the mome raths outgrabe.   

“Beware the Jabberwock, my son!   
      The jaws that bite, the claws that catch!   
Beware the Jubjub bird, and shun   
      The frumious Bandersnatch!”   

## Second Verse
He took his vorpal sword in hand;   
      Long time the manxome foe he sought—   
So rested he by the Tumtum tree   
      And stood awhile in thought.   

And, as in uffish thought he stood,   
      The Jabberwock, with eyes of flame,   
Came whiffling through the tulgey wood,   
      And burbled as it came!   

## Third Verse
"The sun was shining on the sea,   
      Shining with all his might:   
He did his very best to make   
      The billows smooth and bright —   
And this was odd, because it was   
      The middle of the night.   

The moon was shining sulkily,   
      Because she thought the sun   
Had got no business to be there   
      After the day was done —   
"It's very rude of him," she said,   
      "To come and spoil the fun."   

The sea was wet as wet could be,   
      The sands were dry as dry.   
You could not see a cloud, because   
      No cloud was in the sky:   
No birds were flying overhead —   
      There were no birds to fly.   

The Walrus and the Carpenter   
      Were walking close at hand;   
They wept like anything to see   
      Such quantities of sand:   
If this were only cleared away,'   
      They said, it would be grand!'   


## Last Verse

Poems about Life

We are the sum of experiences that we encounter as we go through life. Day to day struggles and triumphs are experienced by all of the world's creatures. As human beings, when we encounter a challenge, we have freedom to choose how to react. Every decision that we make leads us down a different road. We will never come to exactly the same crossroads. Every decision that we make has significance. The tiniest choice that we make reverberates throughout the entire universe.



Source: http://www.familyfriendpoems.com/poems/life/
